# Generated by Django 4.2 on 2023-05-04 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.SmallIntegerField(choices=[(1, 'SUPER ADMIN'), (2, 'ADMIN'), (3, 'STUDENT')], default=4),
        ),
    ]
