# Generated by Django 4.2 on 2023-05-10 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_level', models.CharField(choices=[('Kindergarten', 'Kindergarten'), ('Primary', 'Primary'), ('Secondary', 'Secondary')], max_length=20, null=True)),
                ('primary_school_type', models.CharField(choices=[('SK', 'SK'), ('SJKC', 'SJKC')], max_length=20, null=True)),
                ('sk_primary_level', models.CharField(choices=[('Standard 1', 'Standard 1'), ('Standard 2', 'Standard 2'), ('Standard 3', 'Standard 3'), ('Standard 4', 'Standard 4'), ('Standard 5', 'Standard 5'), ('Standard 6', 'Standard 6')], max_length=20, null=True)),
                ('enrolled_date', models.DateTimeField(auto_now_add=True)),
                ('classin_phoneNo', models.CharField(max_length=20, null=True)),
                ('parent_phoneNo2', models.CharField(max_length=20, null=True)),
                ('bankreceipt', models.ImageField(blank=True, null=True, upload_to='banktransfer_receipt/')),
                ('student_phoneno', models.CharField(max_length=20, null=True)),
                ('student_ic_number', models.CharField(max_length=20, null=True)),
                ('student_ic_photo', models.ImageField(blank=True, null=True, upload_to='studentic_photo/')),
                ('student_photo', models.ImageField(blank=True, null=True, upload_to='student_photo/')),
                ('school_name', models.CharField(max_length=50)),
                ('know_us_from', models.CharField(choices=[('Facebook', 'Facebook'), ('Instagram', 'Instagram'), ('Google', 'Google'), ('Tik Tok', 'Tik Tok'), ('Friend', 'Friend'), ('小红书', '小红书'), ('Sibling', 'Sibling')], max_length=20, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER ADMIN', 'SUPER ADMIN'), ('ADMIN', 'ADMIN'), ('STUDENT', 'STUDENT')], max_length=20, null=True),
        ),
    ]
