# Generated by Django 4.2 on 2023-05-11 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_student_know_us_from_student_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='know_us_from',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
