# Generated by Django 4.2 on 2023-05-12 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_student_know_us_from'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='bankreceipt',
            new_name='bankin_receipt',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='classin_phoneNo',
            new_name='classin_phoneno',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='parent_phoneNo2',
            new_name='parent_phoneno2',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='enrolled_date',
            new_name='startdate',
        ),
        migrations.AddField(
            model_name='student',
            name='sjkc_level',
            field=models.CharField(choices=[('Standard 1', 'Standard 1'), ('Standard 2', 'Standard 2'), ('Standard 3', 'Standrad 3'), ('Standard 4', 'Standard 4'), ('Standard 5', 'Standard 5'), ('Standard 6', 'Standard 6')], max_length=20, null=True),
        ),
    ]
