# Generated by Django 4.2 on 2023-05-12 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_rename_bankreceipt_student_bankin_receipt_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='sk_primary_level',
            new_name='sk_level',
        ),
    ]
