# Generated by Django 4.2 on 2023-05-12 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_rename_sk_primary_level_student_sk_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='secondary_level',
            field=models.CharField(choices=[('Form 1', 'Form 1'), ('Form 2', 'Form 2'), ('Form 3', 'Form 3'), ('Form 4', 'Form 4'), ('Form 5', 'Form 5'), ('Form 6', 'Form 6')], max_length=20, null=True),
        ),
    ]
