# Generated by Django 4.2 on 2023-08-02 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_admin'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Admin',
            new_name='Admins',
        ),
    ]
