# Generated by Django 4.2 on 2023-08-02 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_rename_admin_admins'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Admins',
            new_name='Admin',
        ),
    ]
