# Generated by Django 4.2 on 2023-08-02 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='targeted_group',
            field=models.CharField(choices=[('', 'Select targeted group'), ('ALL', 'All Users'), ('ADMIN', 'Administrators'), ('STUDENT', 'Students')], max_length=20, null=True),
        ),
    ]
