# Generated by Django 4.2 on 2023-08-15 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_user_reset_token_user_reset_token_expiration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='reset_token',
        ),
        migrations.RemoveField(
            model_name='user',
            name='reset_token_expiration',
        ),
    ]
