# Generated by Django 4.2 on 2023-08-21 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_remove_user_reset_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='terms_and_conditions',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='bankin_receipt',
            field=models.FileField(upload_to='bankin_receipt/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_ic_photo',
            field=models.FileField(upload_to='student_ic_photo/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_phoneno',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_photo',
            field=models.FileField(upload_to='student_photo/'),
        ),
    ]
