# Generated by Django 4.2 on 2023-08-22 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_remove_announcement_admin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tuition_classes',
            name='downlaoded_at',
            field=models.DateField(auto_now=True),
        ),
    ]
