# Generated by Django 4.2 on 2023-08-22 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_tuition_classes_downlaoded_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tuition_classes',
            name='downlaoded_at',
        ),
    ]
