# Generated by Django 4.2 on 2023-08-22 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_remove_tuition_classes_downlaoded_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='tuition_classes',
            name='tutor_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
