# Generated by Django 4.2 on 2023-08-22 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_tuition_classes_tutor_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tuition_Classes',
        ),
    ]
