# Generated by Django 4.2 on 2023-08-22 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_delete_tuition_classes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tuition_Classes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tuition_class_name', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('tuition_class_study_level', models.CharField(max_length=50)),
                ('general_start_time', models.TimeField()),
                ('general_end_time', models.TimeField()),
                ('weekly_day', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=10)),
                ('tutor_name', models.CharField(max_length=100)),
                ('monthly_fee', models.DecimalField(decimal_places=2, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.admin')),
            ],
        ),
    ]
