# Generated by Django 4.2 on 2023-08-22 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_tuition_classes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tuition_classes',
            name='monthly_fee',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=8, null=True),
        ),
    ]
