# Generated by Django 4.2 on 2023-08-23 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_alter_tuition_classes_monthly_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tuition_classes',
            name='weekly_day',
            field=models.CharField(choices=[('Mon', 'Monday'), ('Tues', 'Tuesday'), ('Wed', 'Wednesday'), ('Thu', 'Thursday'), ('Fri', 'Friday'), ('Sat', 'Saturday'), ('Sun', 'Sunday')], max_length=10),
        ),
    ]
