# Generated by Django 4.2 on 2023-08-24 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_enrolment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar_Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_description', models.CharField(max_length=100)),
                ('event_type', models.CharField(choices=[('holiday', 'Holiday'), ('meeting', 'Meeting'), ('event', 'Event')], max_length=20)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
