# Generated by Django 4.2 on 2023-08-24 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_calendar_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar_events',
            name='event_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
