# Generated by Django 4.2 on 2023-09-07 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_calendar_events_event_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='classin_phonecode',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
