# Generated by Django 4.2 on 2023-09-29 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_alter_tuition_classes_weekly_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='tuition_classes',
            name='class_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tuition_classes',
            name='class_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
