# Generated by Django 4.2 on 2023-10-03 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0035_tuition_classes_class_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrolment',
            name='request_type',
            field=models.CharField(blank=True, choices=[('Add', 'Add Class'), ('Drop', 'Drop Class')], max_length=4, null=True),
        ),
    ]
