# Generated by Django 4.2 on 2023-10-20 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0037_subject_evaluation'),
    ]

    operations = [
        migrations.AddField(
            model_name='tuition_classes',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tuition_classes',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tuition_classes',
            name='unarchived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
