# Generated by Django 4.2 on 2023-10-28 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0038_tuition_classes_archived_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='unarchived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
