# Generated by Django 4.2 on 2023-10-29 13:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0039_student_archived_at_student_is_archived_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='announcement_posted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
